/mnt/docker/traefik2/traefik.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 0644 root root
    dateext
    dateformat -%Y%m%d
    postrotate
        /usr/bin/docker kill --signal="USR1" traefik || true
    endscript
}
